[package]
name = "spdlog-telegram"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic = "0.5.3"
reqwest = { version = "0.12.24", features = ["blocking"] }
serde_json = "1.0.145"
spdlog-rs = "0.5.1"
thiserror = "2.0.17"
url = "2.5.7"

[dev-dependencies]
mockito = "1.7.0"
